//! Error type for the upbv2-driver.
//!
//! The UPBv2's failure modes are the shared transport-driver common core plus
//! four device-specific variants. The enum, its ASCOM classification,
//! `From<TransportError>`, and the `Result` alias are all generated by
//! [`rusty_photon_driver::driver_error!`]. The codec-layer
//! `From<SessionError<Upbv2CodecError>>` lives in [`crate::codec`] and targets
//! this (local) enum.
//!
//! `WrongModel` deliberately carries no `ascom` arm: the macro's fallthrough
//! maps it to `INVALID_OPERATION`, which is what it means to a client — the
//! request was well-formed but the device is not the one this service drives.
//!
//! `AutoDewControlled` maps to `NOT_IMPLEMENTED` instead, even though "the
//! channel is busy" reads like an operation error. ASCOM couples the Switch
//! write path to `CanWrite`: when `CanWrite` is false, `SetSwitch` and
//! `SetSwitchValue` must raise `MethodNotImplemented`. An auto-dew-driven
//! channel already reports `CanWrite = false`, so any other classification
//! makes the two disagree — which is a `ConformU` issue, not a stylistic
//! choice. The message still names the channel and the Pegasus software.

rusty_photon_driver::driver_error! {
    /// Errors that can occur when interacting with the UPBv2 device.
    pub enum Upbv2Error {
        #[error("invalid switch ID: {0}")]
        InvalidSwitchId(usize),
        #[error("switch not writable: {0}")]
        SwitchNotWritable(usize),
        #[error(
            "cannot write to switch {switch_id} ({channel}): the channel is under \
             auto-dew control. Turn auto-dew off in the Pegasus Astro software first."
        )]
        AutoDewControlled { switch_id: usize, channel: &'static str },
        #[error(
            "device answered {got} — this is a Pegasus {model}, not an Ultimate \
             Powerbox v2. Use the {service} service for it."
        )]
        WrongModel {
            got: String,
            model: &'static str,
            service: &'static str,
        },
    }
    ascom {
        Self::InvalidSwitchId(_) => INVALID_VALUE,
        Self::SwitchNotWritable(_) => NOT_IMPLEMENTED,
        Self::AutoDewControlled { .. } => NOT_IMPLEMENTED,
    }
}
