[package]
name = "libsvbony-sys"
version = "0.1.0"
edition = "2021"
authors = ["Igor von Nyssen <igor@vonnyssen.com>"]
links = "SVBCameraSDK"
repository = "https://github.com/rusty-photon/rusty-photon"
license = "MIT OR Apache-2.0"
description = "Rust bindings for the SVBony camera SDK"
rust-version.workspace = true

[lib]
name = "libsvbony_sys"
path = "lib.rs"

[dependencies]

[lints]
workspace = true
